TINKOFF_ID = '78638'
SBERBANK_ID = '3529'
RZD_ID = '23427'
ROSATOM_ID = '577743'
RUSAGRO_ID = '23186'
FSK_ID = '3607'
ROSTELEKOM_ID = '2748'
YANDEX_ID = '1740'
ROSNEFT_ID = '213221'
GAZPROM_ID = '5778059'
EMPLOYERS_IDS = (
    TINKOFF_ID,
    SBERBANK_ID,
    RZD_ID,
    ROSATOM_ID,
    RUSAGRO_ID,
    FSK_ID,
    ROSTELEKOM_ID,
    YANDEX_ID,
    ROSNEFT_ID,
    GAZPROM_ID
)
EXIT_WORDS = {'q', 'exit', 'quit'}
USER_RESPONSE_CREATE_TABLE = 'create'
USER_RESPONSE_FILL_TABLE = 'fill'
USER_RESPONSE_VAC_COUNT = 'count'
USER_RESPONSE_ALL_VAC = 'all'
USER_RESPONSE_AVG_SALARY = 'avg'
USER_RESPONSE_HIGHER_THAN_AVG_SALARY = 'higher'
USER_RESPONSE_KEYWORD = 'keyword'
VIABLE_RESPONSES = {
    USER_RESPONSE_VAC_COUNT,
    USER_RESPONSE_ALL_VAC,
    USER_RESPONSE_AVG_SALARY,
    USER_RESPONSE_HIGHER_THAN_AVG_SALARY,
    USER_RESPONSE_KEYWORD,
}


